### ISSUE TITLE
BREAK is unfriendly, why not use ERROR or SIGNAL?

### ISSUE THREAD

**Issue by avodonosov** [metawilm/cl-python#18]
cl-pythong source code uses BREAK several in several places.

It's inconvenient. For example, when I do `(ql:quickload :clpython)` on ABCL when testing libraries with cl-test-grid, clpython calls BREAK with message "A CHECKING-READER-CONDITIONALS expression returned zero forms: (CLPYTHON.UTIL:CHECKING-READER-CONDITIONALS)". 

The ABCL process remains hanging, I can't capture this situation programmatically.

It it was ERROR instead of BREAK, test-grig-agent could intercept it using either HANDLER-BIND or *DEBUGGER-HOOK* and record error.

**Comment by metawilm** [comment]
Thanks for the report, I've changed it.

**Comment by avodonosov** [comment]
OK.

BTW, https://common-lisp.net/project/cl-test-grid/library/cl-python.html 
Here you can see results on various lisps for two last Quicklisp releases. As you see, some of the lisps your README declares supported, fail to build cl-python.
