### ISSUE TITLE
Metadata for Quicklisp

### ISSUE THREAD

**Issue by hydandata** [metawilm/cl-python#19]
Please consider adding :description, :author and :license information to your ASDF system(s). This will greatly help Quicklisp users and make it easier for them to report bugs.

More information:

http://blog.quicklisp.org/2015/05/looking-for-more-metadata.html
https://www.quicklisp.org

**Comment by metawilm** [comment]
Thanks for the report. Added in commit ac27ec0ebc22417ae42a9d3f2f9d0290ff8c9ab6.
